[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:mariadb]
command=/usr/sbin/mysqld --user=mysql --datadir=/var/lib/mysql
priority=1
autostart=true
autorestart=true
startretries=30
startsecs=2
stopwaitsecs=10
stopsignal=TERM
stdout_logfile=/var/log/supervisor/mariadb-stdout.log
stderr_logfile=/var/log/supervisor/mariadb-stderr.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=2
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/var/log/supervisor/nginx-stdout.log
stderr_logfile=/var/log/supervisor/nginx-stderr.log

[program:nodejs]
command=/start-node.sh
priority=3
autostart=true
autorestart=true
startretries=30
startsecs=5
stdout_logfile=/var/log/supervisor/nodejs-stdout.log
stderr_logfile=/var/log/supervisor/nodejs-stderr.log
